sudo: required
services:
  - docker

before_install:
  - docker build -t pushpen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pushpen/docker-react npm run test -- --coverage


deploy:
     provider: elasticbeanstalk
     region: "us-east-2"
     app: "docker-react1"
     env: "DcokerReact1-env"
     bucket_name: "elasticbeanstalk-us-east-2-481845461371"
     bucket_path: "docker-react1"
     on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
